### ISSUE TITLE
I'd like to get your opinion

### ISSUE THREAD

**Issue by AndrewHenderson** [AndrewHenderson/underscore.deep#1]
@jmeas In my free time, I started writing some underscore extensions that I'd like to get your opinion on.

I looked around and didn't see anything in places like underscore-contrib that did what I was seeking to do.

I'm working on a PR for Underscore as well.

**Comment by jamesplease** [comment]
Added to my todo list – I'll try to take a look in the next few days!

**Comment by jamesplease** [comment]
Yo again. Had some time to review this this weekend; here are the notez I took:

The name  `underscore.deep` is already a registered npm package for [this lib](https://github.com/Clever/underscore.deep). It's not hugely popular, but it does already have the name, which is a thing :stuck_out_tongue: 

Either way, these tools are cool – I can totally see the value of them. Have you done performance tests to see how it compares against other algorithms using tools built into Lodash or Underscore?

# 

As an aside, I'm a proponent of more-flat data structures, rather than infinitely-nested ones like the one in this README.

The difference is that right now, the data you have is a tree of relationships. The root nodes are the eldest grandparents. I'd prefer to work with an array of **all people** – be they children, parents, or grandparents. Then each person might have a `relationships` field that describes their children / parents / whatever other relationships you might need.

My preference for this just comes from using [JSON API](http://jsonapi.org/), which has a super flexible way of encoding relationships that has been generic-enough for my purposes.

But there's nothing wrong with the nested structure like this, if it's working well for you. I've worked on more projects that use nested data than a more-flat structure, and they've all worked out well :)

**Comment by AndrewHenderson** [comment]
@jmeas Awesome thanks for looking it over.

I didn't know that lib. It seems interesting but doesn't appear to have functions that do what I need. I was thinking about renaming anyway, so this is good reason :+1: Also, I plan to create a PR against both Underscore and Lodash, so this lib might be obsolete if either lib merges.

I agree, flatter, JSON API like data structure is my preference, but not always what you're provided - for instance Twitter API.

On a side note, we've begun using JSON API at CR for new endpoints! It's been an interesting experience and we've already come across a few tricky cases for which JSON API spec doesn't offer any solution. Would be fun to show you how we solved them, consulting aside :wink: 

What's new with you?

**Comment by jamesplease** [comment]
> On a side note, we've begun using JSON API at CR for new endpoints!

Oh, awesome!

> It's been an interesting experience and we've already come across a few tricky cases for which JSON API spec doesn't offer any solution. Would be fun to show you how we solved them, consulting aside :wink:

Interesting! I'd def. like to hear more about this. There's [a forum](http://discuss.jsonapi.org/) for situations like those, where you can get feedback from the authors and/or help develop additions to the spec. You might want to register there and look around to see if anyone else had a similar problem. But yeah in the meantime you should make a secret gist that describes the problem and send me it (I think you have my email, right? :P ).

> What's new with you?

Not too much...though I'm missing the LA weather quite a bit :stuck_out_tongue:

**Comment by AndrewHenderson** [comment]
@jmeas I don't have your email, btw. Send it to me here or at andrewmhenderson@gmail.com

**Comment by jamesplease** [comment]
Sent!
